# Generated by Django 6.0.7 on 2026-07-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='image',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='image_file_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageupload',
            name='image_url',
            field=models.URLField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
